name: Release to Maven Central

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: liberica

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to Maven Central
        env:
          GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
        run: |
          # convert \n -> real newlines, store in var
          IN_MEMORY_KEY="$(printf '%b' "$GPG_KEY")"
          
          ./gradlew :core:publishToMavenCentral \
            -Pversion=${{ github.ref_name }} \
            -PsigningInMemoryKey="$IN_MEMORY_KEY" \
            -PsigningInMemoryKeyId="$GPG_KEY_ID" \
            -PsigningInMemoryKeyPassword="$GPG_PASSPHRASE" \
            -PsigningInMemoryKeyIsBase64=false \
            -PmavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }} \
            -PmavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}
